In [1]:
from euroleague_api.EuroLeagueData import EuroLeagueData
from euroleague_api.boxscore_data import BoxScoreData
from euroleague_api.player_stats import PlayerStats

import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

In [2]:
previous_season = 2023
current_season = 2024
game_code = 1
competition_code = "E"

season_data = EuroLeagueData(competition_code)
df_season_data_previous = season_data.get_game_metadata_season(season=previous_season)
df_season_data_current = season_data.get_game_metadata_season(season=current_season)

In [3]:
df_season_data_current.head()

,round,gameday,date,time,gamenumber,gamecode,group,hometeam,homecode,homescore,awayteam,awaycode,awayscore,played
0,RS,1,"Oct 03, 2024",18:45,1,E2024_1,Regular Season,ALBA BERLIN,BER,77,PANATHINAIKOS AKTOR ATHENS,PAN,87,True
1,RS,2,"Oct 11, 2024",20:30,17,E2024_17,Regular Season,FC BARCELONA,BAR,88,ALBA BERLIN,BER,73,True
2,RS,1,"Oct 03, 2024",19:00,3,E2024_3,Regular Season,ZALGIRIS KAUNAS,ZAL,74,FC BARCELONA,BAR,67,True
3,RS,2,"Oct 09, 2024",19:00,10,E2024_10,Regular Season,AS MONACO,MCO,85,MACCABI PLAYTIKA TEL AVIV,TEL,79,True
4,RS,1,"Oct 04, 2024",21:00,9,E2024_9,Regular Season,VIRTUS SEGAFREDO BOLOGNA,VIR,67,ANADOLU EFES ISTANBUL,IST,76,True

In [4]:
df_season_data = pd.concat([df_season_data_previous, df_season_data_current])

In [5]:
# Combine the 'date' and 'time' columns into a single column
df_season_data['datetime'] = df_season_data['date'] + ' ' + df_season_data['time']

# Convert the combined column into a datetime object
df_season_data['datetime'] = pd.to_datetime(df_season_data['datetime'], format='%b %d, %Y %H:%M')

# drop date, time
df_season_data.drop(['date', 'time'], inplace=True, axis=1)

In [6]:
df_season_data = df_season_data.sort_values(by='datetime')

In [7]:
df_season_data.tail(10)

,round,gameday,gamenumber,gamecode,group,hometeam,homecode,homescore,awayteam,awaycode,awayscore,played,datetime
7,RS,1,8,E2024_8,Regular Season,PARIS BASKETBALL,PRS,77,CRVENA ZVEZDA MERIDIANBET BELGRADE,RED,80,True,2024-10-04 21:00:00
3,RS,2,10,E2024_10,Regular Season,AS MONACO,MCO,85,MACCABI PLAYTIKA TEL AVIV,TEL,79,True,2024-10-09 19:00:00
8,RS,2,11,E2024_11,Regular Season,CRVENA ZVEZDA MERIDIANBET BELGRADE,RED,78,BASKONIA VITORIA-GASTEIZ,BAS,71,True,2024-10-09 20:00:00
13,RS,2,12,E2024_12,Regular Season,ANADOLU EFES ISTANBUL,IST,78,FENERBAHCE BEKO ISTANBUL,ULK,83,True,2024-10-10 19:30:00
12,RS,2,13,E2024_13,Regular Season,LDLC ASVEL VILLEURBANNE,ASV,87,VIRTUS SEGAFREDO BOLOGNA,VIR,85,True,2024-10-10 20:00:00
11,RS,2,14,E2024_14,Regular Season,PANATHINAIKOS AKTOR ATHENS,PAN,94,FC BAYERN MUNICH,MUN,79,True,2024-10-10 20:15:00
9,RS,2,15,E2024_15,Regular Season,REAL MADRID,MAD,93,PARTIZAN MOZZART BET BELGRADE,PAR,86,True,2024-10-10 20:45:00
5,RS,2,18,E2024_18,Regular Season,OLYMPIACOS PIRAEUS,OLY,74,ZALGIRIS KAUNAS,ZAL,68,True,2024-10-11 20:15:00
1,RS,2,17,E2024_17,Regular Season,FC BARCELONA,BAR,88,ALBA BERLIN,BER,73,True,2024-10-11 20:30:00
17,RS,2,16,E2024_16,Regular Season,EA7 EMPORIO ARMANI MILAN,MIL,79,PARIS BASKETBALL,PRS,74,True,2024-10-11 20:30:00

In [ ]:
boxscore = BoxScoreData(competition_code)

boxscore.get_boxscore_data(season=current_season,gamecode=1, boxscore_type='Stats')

In [ ]:
boxscore.get_player_boxscore_stats_data(season=current_season, gamecode=1).iloc[14]

In [12]:
alba_pao = boxscore.get_player_boxscore_stats_data(season=current_season, gamecode=1)

In [13]:
alba_pao

,Season,Gamecode,Home,Player_ID,IsStarter,IsPlaying,Team,Dorsal,Player,Minutes,...,TotalRebounds,Assistances,Steals,Turnovers,BlocksFavour,BlocksAgainst,FoulsCommited,FoulsReceived,Valuation,Plusminus
0,2024,1,1,P012099,0.0,0.0,BER,2,"GROSBER, DORIAN",DNP,...,0,0,0,0,0,0,0,0,0,0.0
1,2024,1,1,P008173,0.0,0.0,BER,3,"SPAGNOLO, MATTEO",16:18,...,1,2,0,1,0,0,2,1,4,-6.0
2,2024,1,1,P011934,0.0,0.0,BER,5,"WETZELL, YANNI",19:03,...,7,0,0,2,0,0,0,1,8,-12.0
3,2024,1,1,P008062,0.0,0.0,BER,7,"MCDOWELL-WHITE, WILL",15:15,...,1,1,0,1,0,0,1,0,12,-8.0
4,2024,1,1,P007025,1.0,1.0,BER,9,"MATTISSECK, JONAS",21:09,...,1,0,1,0,0,1,4,1,1,-7.0
5,2024,1,1,P006251,0.0,0.0,BER,10,"SCHNEIDER, TIM",DNP,...,0,0,0,0,0,0,0,0,0,0.0
6,2024,1,1,P008780,1.0,1.0,BER,15,"HERMANNSSON, MARTIN",27:18,...,2,9,0,3,0,0,2,3,18,1.0
7,2024,1,1,P006919,1.0,0.0,BER,19,"OLINDE, LOUIS",25:18,...,4,1,0,0,0,0,1,2,3,-10.0
8,2024,1,1,P010791,1.0,1.0,BER,21,"KOUMADJE, KHALIFA",22:25,...,13,0,0,1,0,0,1,2,18,-6.0
9,2024,1,1,P011631,1.0,0.0,BER,25,"RAPIEQUE, ELIAS",10:49,...,1,1,1,1,0,0,2,0,-1,0.0
10,2024,1,1,P012721,0.0,1.0,BER,34,"BEAN, JUSTIN",18:08,...,5,1,0,0,0,0,0,1,12,6.0
11,2024,1,1,P012604,0.0,1.0,BER,50,"WILLIAMS, TREVION",24:17,...,4,4,0,2,1,0,3,0,8,-8.0
12,2024,1,1,Team,0.0,0.0,BER,,Team,None,...,1,0,0,0,0,0,0,0,1,NaN
13,2024,1,1,Total,NaN,NaN,BER,NaN,Total,200:00,...,40,19,2,11,1,1,16,11,84,NaN
14,2024,1,0,P011209,0.0,0.0,PAN,0,"KALAITZAKIS, PANAGIOTIS",00:50,...,0,0,0,0,0,0,0,0,0,-5.0
15,2024,1,0,P009622,1.0,0.0,PAN,2,"BROWN, LORENZO",20:11,...,2,5,0,1,0,0,2,2,8,15.0
16,2024,1,0,P001926,0.0,1.0,PAN,10,"SLOUKAS, KOSTAS",16:00,...,0,5,0,0,0,0,0,5,15,5.0
17,2024,1,0,P004088,0.0,0.0,PAN,16,"OSMAN, CEDI",14:39,...,1,1,1,0,1,0,0,0,7,-2.0
18,2024,1,0,P005161,0.0,0.0,PAN,21,"PAPAPETROU, IOANNIS",DNP,...,0,0,0,0,0,0,0,0,0,0.0
19,2024,1,0,P011204,0.0,1.0,PAN,22,"GRANT, JERIAN",21:16,...,1,2,1,0,0,0,1,1,11,-4.0
20,2024,1,0,P012774,1.0,1.0,PAN,25,"NUNN, KENDRICK",32:13,...,3,4,1,0,0,1,2,3,15,15.0
21,2024,1,0,P003842,1.0,1.0,PAN,26,"LESSORT, MATHIAS",27:08,...,8,1,2,0,0,0,1,2,23,8.0
22,2024,1,0,P002328,1.0,0.0,PAN,40,"GRIGONIS, MARIUS",17:15,...,2,1,0,2,0,0,1,2,1,11.0
23,2024,1,0,P012712,0.0,1.0,PAN,41,"HERNANGOMEZ, JUANCHO",21:16,...,1,2,1,0,0,0,0,0,12,-3.0
24,2024,1,0,P007866,1.0,0.0,PAN,44,"MITOGLOU, KONSTANTINOS",14:56,...,4,0,1,0,0,0,3,1,8,7.0
25,2024,1,0,P005353,0.0,0.0,PAN,77,"YURTSEVEN, OMER",14:16,...,3,0,0,0,0,0,1,0,10,3.0
26,2024,1,0,Team,0.0,0.0,PAN,,Team,None,...,3,0,0,1,0,0,0,0,2,NaN
27,2024,1,0,Total,NaN,NaN,PAN,NaN,Total,200:00,...,28,21,7,4,1,1,11,16,112,NaN