In [1]:
# scrape all data from 2023-24 season

import requests
import pandas as pd


url = "https://live.euroleague.net/api/Boxscore?gamecode=1&seasoncode=E2024"
r = requests.get(url)


print(r.status_code)  # if all goes well this must return 200
data = r.json()

200

In [2]:
print(data['Stats'][0]['Team'])
print(data['Stats'][0]['Coach'])
print(data['Stats'][0]['totr']['Points'])

ALBA BERLIN
GONZALEZ, ISRAEL
77

In [3]:
data['Stats'][0].keys()

dict_keys(['Team', 'Coach', 'PlayersStats', 'tmr', 'totr'])

In [ ]:
Coach_stats = pd.DataFrame()

In [26]:
Stats = data['Stats']

In [37]:
player_stats_home = pd.DataFrame(Stats[0]['PlayersStats'])
player_stats_away = pd.DataFrame(Stats[1]['PlayersStats'])

,Player_ID,IsStarter,IsPlaying,Team,Dorsal,Player,Minutes,Points,FieldGoalsMade2,FieldGoalsAttempted2,...,TotalRebounds,Assistances,Steals,Turnovers,BlocksFavour,BlocksAgainst,FoulsCommited,FoulsReceived,Valuation,Plusminus
0,P011209,0,0,PAN,0,"KALAITZAKIS, PANAGIOTIS",00:50,0,0,0,...,0,0,0,0,0,0,0,0,0,-5
1,P009622,1,0,PAN,2,"BROWN, LORENZO",20:11,5,2,3,...,2,5,0,1,0,0,2,2,8,15
2,P001926,0,1,PAN,10,"SLOUKAS, KOSTAS",16:00,10,1,3,...,0,5,0,0,0,0,0,5,15,5
3,P004088,0,0,PAN,16,"OSMAN, CEDI",14:39,5,1,1,...,1,1,1,0,1,0,0,0,7,-2
4,P005161,0,0,PAN,21,"PAPAPETROU, IOANNIS",DNP,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,P011204,0,1,PAN,22,"GRANT, JERIAN",21:16,10,2,4,...,1,2,1,0,0,0,1,1,11,-4
6,P012774,1,1,PAN,25,"NUNN, KENDRICK",32:13,16,4,9,...,3,4,1,0,0,1,2,3,15,15
7,P003842,1,1,PAN,26,"LESSORT, MATHIAS",27:08,14,6,7,...,8,1,2,0,0,0,1,2,23,8
8,P002328,1,0,PAN,40,"GRIGONIS, MARIUS",17:15,3,0,1,...,2,1,0,2,0,0,1,2,1,11
9,P012712,0,1,PAN,41,"HERNANGOMEZ, JUANCHO",21:16,11,1,2,...,1,2,1,0,0,0,0,0,12,-3
10,P007866,1,0,PAN,44,"MITOGLOU, KONSTANTINOS",14:56,5,0,0,...,4,0,1,0,0,0,3,1,8,7
11,P005353,0,0,PAN,77,"YURTSEVEN, OMER",14:16,8,4,4,...,3,0,0,0,0,0,1,0,10,3